workflows:
  android-workflow:
    name: Android Build (Debug)
    max_build_duration: 120
    environment:
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.example.livedub"

    scripts:
      - name: Set up local.properties
        script: |
          cd livedub_android
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Enable AndroidX
        script: |
          cd livedub_android
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties

      - name: Build Android Debug APK
        script: |
          cd livedub_android
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - livedub_android/app/build/outputs/apk/debug/*.apk
